const works=[
['№2 из серии «Жидкая геометрия»','2018','canvas, print, acrylic, spray, marker',['canvas','print','painting','2018'],null],
['№1 и №3 из серии 4d/4p(+p)','2018','canvas, layered print, mixed media',['canvas','print','mixed-media','2018'],null],
['Без названия','2023','canvas, cardboard, acrylic, markers',['canvas','painting','2023'],null],
['BeoSad №1','2023','canvas, cardboard, acrylic, markers',['canvas','painting','2023'],null],
['Из серии «Единственно возможное состояние»','2022','canvas, print, aerosol paint',['canvas','print','2022'],null],
['Prelomitel’ 1','2022','canvas, oil, acrylic, spray, marker',['canvas','painting','2022'],null],
['Путь из замка','2022','canvas, acrylic, aerosol paint',['canvas','painting','2022'],null],
['Подзаголовок: Источник I','2022','canvas, oil, aerosol paint, acrylic, latex',['canvas','painting','2022'],null],
['Сошествие 4','2021','canvas, oil, acrylic, spray',['canvas','painting','2021'],null],
['Посмотри наверх','2021','canvas, acrylic, oil, latex, aerosol paint',['canvas','painting','2021'],null],
['Оранжевое сияние','2021','canvas, aerosol paint',['canvas','painting','2021'],null],
['The Sprinter','2021','canvas, layered print, aerosol paint, acrylic, marker',['canvas','print','2021'],null],
['Rocky','2020','canvas, oil, acrylic, latex, spray, marker',['canvas','painting','2020'],null],
['№2 из серии «Caustic windows»','2020','canvas, acrylic, aerosol paint, marker, print',['canvas','print','2020'],null],
['pole3_ef','2020','acrylic, marker, print',['print','mixed-media','2020'],null],
['Фрагменты любовной речи','2021','canvas, print, acrylic, aerosol paint, glitter varnish',['canvas','print','2021'],null],
['Sklon','2018–2020','canvas, acrylic, latex, aerosol paint',['canvas','painting','2020'],null],
['Лыжная прогулка','2017–2020','canvas, acrylic, aerosol paint, latex',['canvas','painting','2020'],null],
['Quad-1','2020','canvas, aerosol paint, acrylic',['canvas','painting','2020'],null],
['И вот что мне удалось от неё узнать','2020','canvas, acrylic, aerosol paint, marker',['canvas','painting','2020'],null],
['Без звука (№1)','2020','canvas, print, spray',['canvas','print','2020'],null],
['Street Spearit','2020','canvas, acrylic, layered print, latex',['canvas','print','2020'],null],
['Капля на слепом пятне','2020','canvas, acrylic, latex, print, spray',['canvas','print','2020'],null],
['Львиный хребет','2020','canvas, acrylic, marker, spray, mixed media',['canvas','mixed-media','2020'],null],
['Повышенная флажность №2','2016','canvas, acrylic, latex, marker, aerosol paint, print',['canvas','print','2016'],null],
['№6 из серии «Взрывы»','2016','canvas, print, reflective film, interference acrylic',['canvas','print','2016'],null],
['Ворота в сад','2017','paper, acrylic, aerosol paint, latex',['paper','painting','2017'],null],
['№4 из серии «Trypophobia trips»','2017','banner, eyelets, mixed media',['mixed-media','2017'],null],
['Liquid jungle','2017','canvas, acrylic, latex, aerosol, marker',['canvas','painting','2017'],null],
['Korona','2018','paper, mixed media',['paper','mixed-media','2018'],null],
['№2 из серии «Up To Date»','2018','canvas, acrylic, spray, marker',['canvas','painting','2018'],null],
['Poehali','2019','canvas, layered print, acrylic, latex, spray, marker',['canvas','print','2019'],null],
['Огнедышащая лошадка','2019','canvas, acrylic, pastel, oil, aerosol paint',['canvas','painting','2019'],null],
['Оранжевое сияние 2','2019–2022','canvas, oil, acrylic, aerosol paint',['canvas','painting','2022'],null],
['IDM №2. Ownwlcrwnn','2013','paper, mixed media',['paper','mixed-media','2013'],null],
['IDMburger #1','2013','paper, mixed media',['paper','mixed-media','2013'],null],
['IDM #16 FOG7','2013','paper, mixed media',['paper','mixed-media','2013'],null],
['sDonavydachi.net (2)','2017','canvas print, acrylic, latex, oil, spray, marker, pencil, pen',['canvas','print','2017'],null],
['Suck My dick TM color','2009','cardboard, mixed media, 700 × 1000 mm',['mixed-media','cardboard','2009'],'img/2009/Suck My dick TM color, 2009, картон, смешанная техника, 700 × 1000 мм.jpg'],
['Spring','2009','cardboard, oil, 700 × 1000 mm',['painting','cardboard','2009'],'img/2009/Весна, 2009, картон, масло, 700 × 1000 мм.JPG'],
['Selected Line','2009','cardboard, mixed media, 1000 × 700 mm',['mixed-media','cardboard','2009'],'img/2009/Выделенная линия, 2009, картон, смешанная техника, 1000 × 700 мм.JPG'],
['Golden Machine','2009','cardboard, oil, enamel, 1000 × 700 mm',['painting','cardboard','2009'],'img/2009/Золотая машина, 2009, картон, масло, эмаль, 1000 × 700 мм.JPG'],
['Line of Fire','2009','cardboard, mixed media, 700 × 1000 mm',['mixed-media','cardboard','2009'],'img/2009/Линия огня, 2009, картон, смешанная техника, 700 × 1000 мм.JPG'],
['Forgiveness Sunday','2009','cardboard, oil, 1000 × 700 mm',['painting','cardboard','2009'],'img/2009/Прощенное воскресенье, 2009, картон, масло, 1000 × 700 мм.JPG'],
['Good Friday','2009','cardboard, acrylic, oil, collage, 1000 × 700 mm',['mixed-media','collage','2009'],'img/2009/Страстная пятница, 2009, картон, акрил, масло, коллаж, 1000 × 700 мм.JPG'],
['Trinity','2009','cardboard, oil, acrylic spray, 1000 × 700 mm',['painting','cardboard','2009'],'img/2009/Троица, 2009, картон, масло, акриловый спрей, 1000 × 700 мм.JPG'],
['Message #1','2010','cardboard, oil, 1000 × 700 mm',['painting','cardboard','2010'],'img/2010/Message#1, 2010, картон, масло, 1000 × 700 мм.jpg'],
['Bezoshobochnost','2010','cardboard, acrylic, plaster, 700 × 1000 mm',['mixed-media','cardboard','2010'],'img/2010/Безошибочность, 2010, картон, акрил, штукатурка, 700 × 1000 мм.jpg'],
['Biennale','2010','cardboard, acrylic, spray, 1000 × 700 mm',['mixed-media','cardboard','2010'],'img/2010/Биеннале, 2010, картон, акрил, спрей, 1000 × 700 мм.JPG'],
['Komarov Boulevard','2010','hardboard, oil, 1290 × 520 mm',['painting','hardboard','2010'],'img/2010/Бульвар Комарова, 2010, ДСП, масло, 1290 × 520 мм.jpg'],
['Sifreddi-11','2011','hardboard, acrylic, 1650 × 550 mm',['painting','hardboard','2011'],'img/2011/Sifreddi-11, 2011, ДСП, акрил, 1650 × 550 мм.jpg'],
['Masterpiece','2011','canvas, acrylic, spray',['painting','canvas','2011'],'img/2011/6) Шедевр, 2011, холст, акрил, спрей.jpg'],
['All Is Fall (unfinished)','2011','hardboard, acrylic',['painting','hardboard','2011'],'img/2011/All Is Fall (не законченная), 2011, ДСП, акрил.JPG'],
['Two Shelves (diptych, in memory of Jackson Pollock)','2011','plywood, acrylic, 850 × 330 mm each',['mixed-media','plywood','2011'],'img/2011/Две полки (диптих, памяти Джексона Поллока), 2011, фанера, акрил, 850 × 330 мм (каждая часть).jpg']
];
const grid=document.getElementById('works-grid');let filter='all',sort='year';
function render(){if(!grid)return;let list=works.filter(w=>filter==='all'||w[3].includes(filter));list.sort((a,b)=>sort==='year'?parseInt(b[1])-parseInt(a[1]):a[2].localeCompare(b[2]));grid.innerHTML=list.map(w=>`<article class="work-card ${w[4]?'has-image':''}" data-image="${w[4]||''}"><div class="work-image">${w[4]?`<img src="${encodeURI(w[4])}" alt="${w[0]}" loading="lazy">`:`<span>WORK / ${w[1]}</span>`}</div><div class="work-info"><div class="work-title">${w[0]}</div><div class="work-meta"><span>${w[1]}</span><span>${w[2]}</span></div><div class="work-tags">${w[3].map(t=>`<button class="tag" data-filter="${t}">#${t}</button>`).join('')}</div></div></article>`).join('')}
document.addEventListener('click',e=>{const f=e.target.closest('[data-filter]');const s=e.target.closest('[data-sort]');const card=e.target.closest('.work-card.has-image');if(f){filter=f.dataset.filter;document.querySelectorAll('[data-filter]').forEach(x=>x.classList.toggle('active',x.dataset.filter===filter));render();return}if(s){sort=s.dataset.sort;document.querySelectorAll('[data-sort]').forEach(x=>x.classList.toggle('active',x.dataset.sort===sort));render();return}if(card){const box=document.getElementById('lightbox'),img=document.getElementById('lightbox-image'),caption=document.getElementById('lightbox-caption');img.src=encodeURI(card.dataset.image);img.alt=card.querySelector('.work-title').textContent;caption.textContent=card.querySelector('.work-title').textContent+' · '+card.querySelector('.work-meta').innerText;box.classList.add('open');box.setAttribute('aria-hidden','false')}});
document.getElementById('lightbox-close')?.addEventListener('click',()=>{const b=document.getElementById('lightbox');b.classList.remove('open');b.setAttribute('aria-hidden','true')});document.getElementById('lightbox')?.addEventListener('click',e=>{if(e.target.id==='lightbox'){e.currentTarget.classList.remove('open');e.currentTarget.setAttribute('aria-hidden','true')}});document.addEventListener('keydown',e=>{if(e.key==='Escape')document.getElementById('lightbox')?.classList.remove('open')});render();