const works=[
['№2 из серии «Жидкая геометрия»','2018','canvas, print, acrylic, spray, marker',['canvas','print','painting','2018']],
['№1 и №3 из серии 4d/4p(+p)','2018','canvas, layered print, mixed media',['canvas','print','mixed-media','2018']],
['Без названия','2023','canvas, cardboard, acrylic, markers',['canvas','painting','2023']],
['BeoSad №1','2023','canvas, cardboard, acrylic, markers',['canvas','painting','2023']],
['Из серии «Единственно возможное состояние»','2022','canvas, print, aerosol paint',['canvas','print','2022']],
['Prelomitel’ 1','2022','canvas, oil, acrylic, spray, marker',['canvas','painting','2022']],
['Путь из замка','2022','canvas, acrylic, aerosol paint',['canvas','painting','2022']],
['Подзаголовок: Источник I','2022','canvas, oil, aerosol paint, acrylic, latex',['canvas','painting','2022']],
['Сошествие 4','2021','canvas, oil, acrylic, spray',['canvas','painting','2021']],
['Посмотри наверх','2021','canvas, acrylic, oil, latex, aerosol paint',['canvas','painting','2021']],
['Оранжевое сияние','2021','canvas, aerosol paint',['canvas','painting','2021']],
['The Sprinter','2021','canvas, layered print, aerosol paint, acrylic, marker',['canvas','print','2021']],
['Rocky','2020','canvas, oil, acrylic, latex, spray, marker',['canvas','painting','2020']],
['№2 из серии «Caustic windows»','2020','canvas, acrylic, aerosol paint, marker, print',['canvas','print','2020']],
['pole3_ef','2020','acrylic, marker, print',['print','mixed-media','2020']],
['Фрагменты любовной речи','2021','canvas, print, acrylic, aerosol paint, glitter varnish',['canvas','print','2021']],
['Sklon','2018–2020','canvas, acrylic, latex, aerosol paint',['canvas','painting','2020']],
['Лыжная прогулка','2017–2020','canvas, acrylic, aerosol paint, latex',['canvas','painting','2020']],
['Quad-1','2020','canvas, aerosol paint, acrylic',['canvas','painting','2020']],
['И вот что мне удалось от неё узнать','2020','canvas, acrylic, aerosol paint, marker',['canvas','painting','2020']],
['Без звука (№1)','2020','canvas, print, spray',['canvas','print','2020']],
['Street Spearit','2020','canvas, acrylic, layered print, latex',['canvas','print','2020']],
['Капля на слепом пятне','2020','canvas, acrylic, latex, print, spray',['canvas','print','2020']],
['Львиный хребет','2020','canvas, acrylic, marker, spray, mixed media',['canvas','mixed-media','2020']],
['Повышенная флажность №2','2016','canvas, acrylic, latex, marker, aerosol paint, print',['canvas','print','2016']],
['№6 из серии «Взрывы»','2016','canvas, print, reflective film, interference acrylic',['canvas','print','2016']],
['Ворота в сад','2017','paper, acrylic, aerosol paint, latex',['paper','painting','2017']],
['№4 из серии «Trypophobia trips»','2017','banner, eyelets, mixed media',['mixed-media','2017']],
['Liquid jungle','2017','canvas, acrylic, latex, aerosol, marker',['canvas','painting','2017']],
['Korona','2018','paper, mixed media',['paper','mixed-media','2018']],
['№2 из серии «Up To Date»','2018','canvas, acrylic, spray, marker',['canvas','painting','2018']],
['Poehali','2019','canvas, layered print, acrylic, latex, spray, marker',['canvas','print','2019']],
['Огнедышащая лошадка','2019','canvas, acrylic, pastel, oil, aerosol paint',['canvas','painting','2019']],
['Оранжевое сияние 2','2019–2022','canvas, oil, acrylic, aerosol paint',['canvas','painting','2022']],
['IDM №2. Ownwlcrwnn','2013','paper, mixed media',['paper','mixed-media','2013']],
['IDMburger #1','2013','paper, mixed media',['paper','mixed-media','2013']],
['IDM #16 FOG7','2013','paper, mixed media',['paper','mixed-media','2013']],
['sDonavydachi.net (2)','2017','canvas print, acrylic, latex, oil, spray, marker, pencil, pen',['canvas','print','2017']]
];
const grid=document.getElementById('works-grid');let filter='all',sort='year';
function render(){if(!grid)return;let list=works.filter(w=>filter==='all'||w[3].includes(filter));list.sort((a,b)=>sort==='year'?parseInt(b[1])-parseInt(a[1]):a[2].localeCompare(b[2]));grid.innerHTML=list.map((w,i)=>`<article class="work-card"><div class="work-image"><span>WORK / ${w[1]}</span></div><div class="work-info"><div class="work-title">${w[0]}</div><div class="work-meta"><span>${w[1]}</span><span>${w[2]}</span></div><div class="work-tags">${w[3].map(t=>`<button class="tag" data-filter="${t}">#${t}</button>`).join('')}</div></div></article>`).join('')}
document.addEventListener('click',e=>{const f=e.target.closest('[data-filter]');const s=e.target.closest('[data-sort]');if(f){filter=f.dataset.filter;document.querySelectorAll('[data-filter]').forEach(x=>x.classList.toggle('active',x.dataset.filter===filter));render()}if(s){sort=s.dataset.sort;document.querySelectorAll('[data-sort]').forEach(x=>x.classList.toggle('active',x.dataset.sort===sort));render()}});render();
